Traceback (most recent call last):
  File "main.py", line 3, in <module>
    print"hello"
IOError: [Errno 27] File too large
