Traceback (most recent call last):
  File "main.py", line 3, in <module>
    os.chroot("/mnt/new_root")
OSError: [Errno 2] No such file or directory: '/mnt/new_root'
