Traceback (most recent call last):
  File "main.py", line 4, in <module>
    print "a",
IOError: [Errno 27] File too large
