Traceback (most recent call last):
  File "main.py", line 3, in <module>
    print "1",
IOError: [Errno 27] File too large
