Traceback (most recent call last):
  File "main.py", line 4, in <module>
    for i in range(0,1000000000):
MemoryError
