Traceback (most recent call last):
  File "main.py", line 10, in <module>
    prime_check([2, 44, 5, 3, 67, 17])
  File "main.py", line 5, in prime_check
    for x in range(3, int(n**0.5)+1, 2):
NameError: global name 'n' is not defined
